### ISSUE TITLE
when i run evaluation.py  there are some errors as follow :

### ISSUE THREAD

**Issue by uyplayer** [howardhsu/Double-Embeddings-and-CNN-based-Sequence-Labeling-for-Aspect-Extraction#13]
Error: Could not find or load main class Main.Aspects

Caused by: java.lang.ClassNotFoundException: Main.Aspects

subprocess.CalledProcessError: Command '['java', '-cp', 'script/eval.jar', 'Main.Aspects', 'data/official_data/pred.xml', 'data/official_data/Laptops_Test_Gold.xml']' returned non-zero exit status 1.

i do not know  what's wrong here

**Comment by uyplayer** [comment]
Error: Could not find or load main class Main.Aspects
Caused by: java.lang.ClassNotFoundException: Main.Aspects

**Comment by uyplayer** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at gr.ilsp.nlp.semeval.absa.eval.ConsoleAspectsAndCategsExtractionEval.run(ConsoleAspectsAndCategsExtractionEval.java:74)
	at gr.ilsp.nlp.semeval.absa.eval.ConsoleAspectsAndCategsExtractionEval.main(ConsoleAspectsAndCategsExtractionEval.java:243)
	at Main.Aspects.main(Aspects.java:9)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more

**Comment by uyplayer** [comment]
i solve this issue ; because i use java 10 ; after i changed it java 8 ; all running ok ;
